--날짜 형태의 함수--
-- 현재 날짜 및 시간을 내포 하고있는 SYSDATE--
SELECT SYSDATE FROM DUAL;

SELECT SYSDATE+1 FROM DUAL;
SELECT SYSDATE-2 FROM DUAL;

SELECT SYSDATE-28 FROM DUAL;
SELECT SYSDATE+28 FROM DUAL;

-- 날짜 - 날짜 => 날짜와 날짜 사이의 일수--
SELECT * FROM EMP;
SELECT ROUND(SYSDATE - HIREDATE)
FROM EMP;

SELECT HIREDATE, ROUND (HIREDATE, 'MONTH') FROM EMP;


-- 달과 달 사이 몇 개월인제 구하는 함수--
-- 직원들이 입사일부터 오늘까지 몇 개월 일 했는가?--
SELECT ENAME, SYSDATE, HIREDATE,
ROUND(MONTHS_BETWEEN (SYSDATE, HIREDATE)) 
FROM EMP;

--개월 수 더하기
-- 입사일에서 6개월 뒤
SELECT ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 5) FROM EMP;


--NEXT_DAY(날짜, 요일)
-- 날짜로부터 가장 가까운 날의 요일은 몇일인지?
SELECT SYSDATE, NEXT_DAY(SYSDATE-30, '목요일') FROM DUAL;

-- 오늘을 기준으로 7개월 후 가장 가까운 일요일--
SELECT ADD_MONTHS(SYSDATE,7), NEXT_DAY(ADD_MONTHS(SYSDATE, 7), '일요일')
FROM DUAL;

-- 해당 월의 마지막 날 --
SELECT HIREDATE, LAST_DAY(HIREDATE) FROM EMP;


SELECT SYSDATE, TO_CHAR(SYSDATE+365, 'YYYY-MM-DD DAY') FROM DUAL;
SELECT SYSDATE FROM DUAL; --JAVA의 java.sql.Date 클래스로 사용 가능--

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD, HH:MI:SS AM') FROM DUAL;

-- 날짜 및 시간단위까지 필요한 경우 - 주로 게시판에서 많이 사용
-- 날짜만 필요한 경우                     - 쇼핑몰 물품 등록 날짜, 입대일 계산기, 전역일 계산기 등등~~~~


SELECT TO_CHAR (1230000) || '원'  FROM DUAL;
SELECT 1230000 || '원' FROM DUAL;

SELECT TO_CHAR (123456, 'L000,000,000'), TO_CHAR (123456, 'L999,999,999') FROM DUAL;



--문제---
--EMP 테이블에서 사원들의 고용일자 및 요일을 출력

SELECT TO_CHAR(HIREDATE, 'YYYY-MM-DD DAY HH24:MI:SS')
FROM EMP;

--TO_DATE => 문자열-> 날짜로
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE=19810220;
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE=TO_DATE('19810220','YYYYMMDD');

SELECT SYSDATE-'2009/01/01' FROM DUAL;
SELECT SYSDATE - TO_DATE('20090101','YYYYMMDD') FROM DUAL;
--데이터베이스에 날짜를 저장 할때는 날짜를(YYYYMMDDHHMISS) 형태 그대로 저장..

SELECT TRUNC(SYSDATE-TO_DATE('2008/01/01', 'YYYY/MM/DD')) FROM DUAL;


--TO_NUMBER -> 문자열을 -> 숫자형태로
SELECT '10000' - '20000' FROM DUAL; -- 권장 x
SELECT TO_NUMBER('10000') - TO_NUMBER('20000') FROM DUAL; --권장 o














